version: '3.9'

services:
  web:
    build: .
    container_name: python_flask_lab
    ports:
      - "8000:8000"  # Maps the host's port 8000 to the container's port 8000
    volumes:
      - .:/app  # Mounts the current directory into the container
    depends_on:
      - mongo  # Ensures MongoDB starts before the web service
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/bananDb  # Set the MongoDB URI environment variable

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"  # Maps the host's port 27017 to the container's port 27017
    volumes:
      - mongo-data:/data/db  # Persists MongoDB data between container restarts

volumes:
  mongo-data:  # Creates a named volume for MongoDB data persistence
